### ISSUE TITLE
Where can find the dataset used in this project(IDEAL dataset) ?

### ISSUE THREAD

**Issue by Hessen525** [cbrewitt/nilm_fcn#1]
Hi,
Thanks for your code, but I can not find IDEAL dataset in your project and paper.
Is it open dataset?

**Comment by cbrewitt** [comment]
Hi Hessen. The dataset will be released publicly soon, and will be available here:
[https://datashare.is.ed.ac.uk/handle/10283/3647](https://datashare.is.ed.ac.uk/handle/10283/3647)

**Comment by Hessen525** [comment]
@cbrewitt Thanks!
